//! Expected column definitions for published `PostgreSQL` schema tracks.

#[derive(Debug, Clone, Copy)]
pub(super) struct PgColumn<'a> {
    pub(super) table: &'a str,
    pub(super) name: &'a str,
    pub(super) data_type: &'a str,
    pub(super) udt_name: &'a str,
    pub(super) nullable: bool,
    pub(super) default: Option<&'a str>,
    pub(super) sequence: bool,
}

pub(super) const PG_CLEAN_COLUMNS: &[PgColumn<'_>] = &[
    PgColumn {
        table: "keepsake_schema_metadata",
        name: "key",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_schema_metadata",
        name: "value",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_relation_definitions",
        name: "id",
        data_type: "uuid",
        udt_name: "uuid",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_relation_definitions",
        name: "kind",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_relation_definitions",
        name: "key",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_relation_definitions",
        name: "enabled",
        data_type: "boolean",
        udt_name: "bool",
        nullable: false,
        default: Some("true"),
        sequence: false,
    },
    PgColumn {
        table: "keepsake_relation_definitions",
        name: "expiry_policy",
        data_type: "jsonb",
        udt_name: "jsonb",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_relation_definitions",
        name: "created_at",
        data_type: "timestamp with time zone",
        udt_name: "timestamptz",
        nullable: false,
        default: Some("now()"),
        sequence: false,
    },
    PgColumn {
        table: "keepsake_relation_definitions",
        name: "updated_at",
        data_type: "timestamp with time zone",
        udt_name: "timestamptz",
        nullable: false,
        default: Some("now()"),
        sequence: false,
    },
    PgColumn {
        table: "keepsakes",
        name: "id",
        data_type: "uuid",
        udt_name: "uuid",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsakes",
        name: "subject_kind",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsakes",
        name: "subject_id",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsakes",
        name: "relation_id",
        data_type: "uuid",
        udt_name: "uuid",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsakes",
        name: "state",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsakes",
        name: "expiry_policy",
        data_type: "jsonb",
        udt_name: "jsonb",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsakes",
        name: "applied_at",
        data_type: "timestamp with time zone",
        udt_name: "timestamptz",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsakes",
        name: "expires_at",
        data_type: "timestamp with time zone",
        udt_name: "timestamptz",
        nullable: true,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsakes",
        name: "fulfilled_at",
        data_type: "timestamp with time zone",
        udt_name: "timestamptz",
        nullable: true,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsakes",
        name: "revoked_at",
        data_type: "timestamp with time zone",
        udt_name: "timestamptz",
        nullable: true,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsakes",
        name: "metadata",
        data_type: "jsonb",
        udt_name: "jsonb",
        nullable: false,
        default: Some("'{}'::jsonb"),
        sequence: false,
    },
    PgColumn {
        table: "keepsakes",
        name: "created_at",
        data_type: "timestamp with time zone",
        udt_name: "timestamptz",
        nullable: false,
        default: Some("now()"),
        sequence: false,
    },
    PgColumn {
        table: "keepsakes",
        name: "updated_at",
        data_type: "timestamp with time zone",
        udt_name: "timestamptz",
        nullable: false,
        default: Some("now()"),
        sequence: false,
    },
    PgColumn {
        table: "keepsake_fulfillment_counters",
        name: "keepsake_id",
        data_type: "uuid",
        udt_name: "uuid",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_fulfillment_counters",
        name: "key",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_fulfillment_counters",
        name: "value",
        data_type: "bigint",
        udt_name: "int8",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_fulfillment_counters",
        name: "observed_at",
        data_type: "timestamp with time zone",
        udt_name: "timestamptz",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_fulfillment_checklist",
        name: "keepsake_id",
        data_type: "uuid",
        udt_name: "uuid",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_fulfillment_checklist",
        name: "item",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_fulfillment_checklist",
        name: "complete",
        data_type: "boolean",
        udt_name: "bool",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_fulfillment_checklist",
        name: "observed_at",
        data_type: "timestamp with time zone",
        udt_name: "timestamptz",
        nullable: false,
        default: None,
        sequence: false,
    },
];

#[cfg(feature = "migrations")]
pub(super) const PG_LEGACY_COLUMNS: &[PgColumn<'_>] = &[
    PgColumn {
        table: "keepsake_audit_events",
        name: "id",
        data_type: "bigint",
        udt_name: "int8",
        nullable: false,
        default: Some("nextval"),
        sequence: true,
    },
    PgColumn {
        table: "keepsake_audit_events",
        name: "keepsake_id",
        data_type: "uuid",
        udt_name: "uuid",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_events",
        name: "relation_id",
        data_type: "uuid",
        udt_name: "uuid",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_events",
        name: "subject_kind",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_events",
        name: "subject_id",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_events",
        name: "actor_kind",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_events",
        name: "actor_id",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_events",
        name: "event_type",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_events",
        name: "decision",
        data_type: "jsonb",
        udt_name: "jsonb",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_events",
        name: "occurred_at",
        data_type: "timestamp with time zone",
        udt_name: "timestamptz",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_events",
        name: "recorded_at",
        data_type: "timestamp with time zone",
        udt_name: "timestamptz",
        nullable: false,
        default: Some("now()"),
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_context_attributes",
        name: "audit_event_id",
        data_type: "bigint",
        udt_name: "int8",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_context_attributes",
        name: "key",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_context_attributes",
        name: "value",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_outbox",
        name: "id",
        data_type: "bigint",
        udt_name: "int8",
        nullable: false,
        default: Some("nextval"),
        sequence: true,
    },
    PgColumn {
        table: "keepsake_audit_outbox",
        name: "audit_event_id",
        data_type: "bigint",
        udt_name: "int8",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_outbox",
        name: "event_type",
        data_type: "text",
        udt_name: "text",
        nullable: false,
        default: Some("'keepsake.audit_event_recorded'"),
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_outbox",
        name: "payload",
        data_type: "jsonb",
        udt_name: "jsonb",
        nullable: false,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_outbox",
        name: "claimed_by",
        data_type: "text",
        udt_name: "text",
        nullable: true,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_outbox",
        name: "claimed_until",
        data_type: "timestamp with time zone",
        udt_name: "timestamptz",
        nullable: true,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_outbox",
        name: "delivered_at",
        data_type: "timestamp with time zone",
        udt_name: "timestamptz",
        nullable: true,
        default: None,
        sequence: false,
    },
    PgColumn {
        table: "keepsake_audit_outbox",
        name: "created_at",
        data_type: "timestamp with time zone",
        udt_name: "timestamptz",
        nullable: false,
        default: Some("now()"),
        sequence: false,
    },
];
