//! Expected column definitions for published `MySQL` and `MariaDB` schema tracks.

#[derive(Debug, Clone, Copy)]
pub(super) struct MySqlColumn<'a> {
    pub(super) table: &'a str,
    pub(super) name: &'a str,
    pub(super) column_type: &'a str,
    pub(super) nullable: bool,
    pub(super) default: Option<&'a str>,
    pub(super) auto_increment: bool,
    pub(super) generated: Option<&'a str>,
}

pub(super) const MYSQL_CLEAN_COLUMNS: &[MySqlColumn<'_>] = &[
    MySqlColumn {
        table: "keepsake_schema_metadata",
        name: "key",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_schema_metadata",
        name: "value",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_relation_definitions",
        name: "id",
        column_type: "char(36)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_relation_definitions",
        name: "kind",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_relation_definitions",
        name: "key",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_relation_definitions",
        name: "enabled",
        column_type: "tinyint(1)",
        nullable: false,
        default: Some("1"),
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_relation_definitions",
        name: "expiry_policy",
        column_type: "json",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_relation_definitions",
        name: "created_at",
        column_type: "datetime(6)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_relation_definitions",
        name: "updated_at",
        column_type: "datetime(6)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "id",
        column_type: "char(36)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "subject_kind",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "subject_id",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "relation_id",
        column_type: "char(36)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "state",
        column_type: "varchar(16)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "expiry_policy",
        column_type: "json",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "applied_at",
        column_type: "datetime(6)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "expires_at",
        column_type: "datetime(6)",
        nullable: true,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "fulfilled_at",
        column_type: "datetime(6)",
        nullable: true,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "revoked_at",
        column_type: "datetime(6)",
        nullable: true,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "metadata",
        column_type: "json",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "created_at",
        column_type: "datetime(6)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "updated_at",
        column_type: "datetime(6)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "active_relation_key",
        column_type: "char(36)",
        nullable: true,
        default: None,
        auto_increment: false,
        generated: Some("case when state = 'applied' then relation_id end"),
    },
    MySqlColumn {
        table: "keepsakes",
        name: "fulfillment_pending",
        column_type: "tinyint(4)",
        nullable: true,
        default: None,
        auto_increment: false,
        generated: Some(
            "case when state = 'applied' and json_unquote(json_extract(expiry_policy, '$.type')) = 'when_fulfilled' then 1 end",
        ),
    },
    MySqlColumn {
        table: "keepsake_fulfillment_counters",
        name: "keepsake_id",
        column_type: "char(36)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_fulfillment_counters",
        name: "key",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_fulfillment_counters",
        name: "value",
        column_type: "bigint",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_fulfillment_counters",
        name: "observed_at",
        column_type: "datetime(6)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_fulfillment_checklist",
        name: "keepsake_id",
        column_type: "char(36)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_fulfillment_checklist",
        name: "item",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_fulfillment_checklist",
        name: "complete",
        column_type: "tinyint(1)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_fulfillment_checklist",
        name: "observed_at",
        column_type: "datetime(6)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
];

pub(super) const MYSQL_V3_TENANT_COLUMNS: &[MySqlColumn<'_>] = &[
    MySqlColumn {
        table: "keepsake_relation_definitions",
        name: "tenant_id",
        column_type: "varbinary(255)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "tenant_id",
        column_type: "varbinary(255)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_fulfillment_counters",
        name: "tenant_id",
        column_type: "varbinary(255)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_fulfillment_checklist",
        name: "tenant_id",
        column_type: "varbinary(255)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
];

pub(super) const MYSQL_V4_TENANT_COLUMNS: &[MySqlColumn<'_>] = &[
    MySqlColumn {
        table: "keepsake_relation_definitions",
        name: "tenant_id",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsakes",
        name: "tenant_id",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_fulfillment_counters",
        name: "tenant_id",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_fulfillment_checklist",
        name: "tenant_id",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
];

pub(super) fn mysql_v3_clean_columns() -> Vec<MySqlColumn<'static>> {
    // MariaDB does not permit a conditional generated expression to read a
    // CHAR column. The v3 baseline therefore uses VARCHAR for UUID text
    // columns, preserving the wire representation while keeping the
    // active-relation projection portable across both MySQL families.
    MYSQL_CLEAN_COLUMNS
        .iter()
        .copied()
        .map(|mut column| {
            if column.column_type == "char(36)" {
                column.column_type = "varchar(36)";
            }
            column
        })
        .collect()
}

#[cfg(feature = "migrations")]
pub(super) const MYSQL_LEGACY_COLUMNS: &[MySqlColumn<'_>] = &[
    MySqlColumn {
        table: "keepsake_audit_events",
        name: "id",
        column_type: "bigint",
        nullable: false,
        default: None,
        auto_increment: true,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_events",
        name: "keepsake_id",
        column_type: "char(36)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_events",
        name: "relation_id",
        column_type: "char(36)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_events",
        name: "subject_kind",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_events",
        name: "subject_id",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_events",
        name: "actor_kind",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_events",
        name: "actor_id",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_events",
        name: "event_type",
        column_type: "varchar(64)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_events",
        name: "decision",
        column_type: "json",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_events",
        name: "occurred_at",
        column_type: "datetime(6)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_events",
        name: "recorded_at",
        column_type: "datetime(6)",
        nullable: false,
        default: Some("current_timestamp(6)"),
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_context_attributes",
        name: "audit_event_id",
        column_type: "bigint",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_context_attributes",
        name: "key",
        column_type: "varchar(191)",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_context_attributes",
        name: "value",
        column_type: "text",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_outbox",
        name: "id",
        column_type: "bigint",
        nullable: false,
        default: None,
        auto_increment: true,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_outbox",
        name: "audit_event_id",
        column_type: "bigint",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_outbox",
        name: "event_type",
        column_type: "text",
        nullable: false,
        default: Some("keepsake.audit_event_recorded"),
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_outbox",
        name: "payload",
        column_type: "json",
        nullable: false,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_outbox",
        name: "claimed_by",
        column_type: "text",
        nullable: true,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_outbox",
        name: "claimed_until",
        column_type: "timestamp(6)",
        nullable: true,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_outbox",
        name: "delivered_at",
        column_type: "timestamp(6)",
        nullable: true,
        default: None,
        auto_increment: false,
        generated: None,
    },
    MySqlColumn {
        table: "keepsake_audit_outbox",
        name: "created_at",
        column_type: "timestamp(6)",
        nullable: false,
        default: Some("current_timestamp(6)"),
        auto_increment: false,
        generated: None,
    },
];
